### PR TITLE
Shifted All Frontend Validations To Backend

### PR DESCRIPTION
**Pull request by shreyas-omkar**
**Shifting The Validations**

- Shifted most of the frontend validations to backend.
- Kept some validations in frontend which were absolutely necessary and not to put too much load on server.
- Also added tests in backend to test formats of email, USN etc.

**Changes Done**

- PBCTF form logic have been shifted to backend.
- PBCTF form was added with some uniqueness checks in backend.
- PBCTF form had DB calls and Logic in frontend which have been shifted to backend for increased security.

### CODE REVIEW

**Comment by SkySingh04** [comment]
@shreyas-omkar is this PR ready to be reviewed?

**Comment by shreyas-omkar** [comment]
Yes sir. 🫡

**Comment by shreyas-omkar** [comment]
Hello @SkySingh04 Bhaiya, Merge Conflicts are Resolved

**Review by SkySingh04 — APPROVED** [review]
LGTM! Amazing work!

**Pull request merged**
